// prevajanje datoteke *.proto:
//   - namestitev modulov
//      module load protobuf
//      module load binutils/2.39-GCCcore-12.2.0
//      go install google.golang.org/protobuf/cmd/protoc-gen-go@latest (samo ob prvi uporabi)
//      go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest (samo ob prvi uporabi)
//      export PATH="$PATH:$(go env GOPATH)/bin"
//   - prevajanje
//      protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative razpravljalnica.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: razpravljalnica/razpravljalnica.proto

package razpravljalnica

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpType int32

const (
	OpType_OP_POST OpType = 0
	OpType_OP_LIKE OpType = 1
)

// Enum value maps for OpType.
var (
	OpType_name = map[int32]string{
		0: "OP_POST",
		1: "OP_LIKE",
	}
	OpType_value = map[string]int32{
		"OP_POST": 0,
		"OP_LIKE": 1,
	}
)

func (x OpType) Enum() *OpType {
	p := new(OpType)
	*p = x
	return p
}

func (x OpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpType) Descriptor() protoreflect.EnumDescriptor {
	return file_razpravljalnica_razpravljalnica_proto_enumTypes[0].Descriptor()
}

func (OpType) Type() protoreflect.EnumType {
	return &file_razpravljalnica_razpravljalnica_proto_enumTypes[0]
}

func (x OpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpType.Descriptor instead.
func (OpType) EnumDescriptor() ([]byte, []int) {
	return file_razpravljalnica_razpravljalnica_proto_rawDescGZIP(), []int{0}
}

type NodeRole int32

const (
	NodeRole_HEAD         NodeRole = 0
	NodeRole_INTERMEDIATE NodeRole = 1
	NodeRole_TAIL         NodeRole = 2
)

// Enum value maps for NodeRole.
var (
	NodeRole_name = map[int32]string{
		0: "HEAD",
		1: "INTERMEDIATE",
		2: "TAIL",
	}
	NodeRole_value = map[string]int32{
		"HEAD":         0,
		"INTERMEDIATE": 1,
		"TAIL":         2,
	}
)

func (x NodeRole) Enum() *NodeRole {
	p := new(NodeRole)
	*p = x
	return p
}

func (x NodeRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeRole) Descriptor() protoreflect.EnumDescriptor {
	return file_razpravljalnica_razpravljalnica_proto_enumTypes[1].Descriptor()
}

func (NodeRole) Type() protoreflect.EnumType {
	return &file_razpravljalnica_razpravljalnica_proto_enumTypes[1]
}

func (x NodeRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeRole.Descriptor instead.
func (NodeRole) EnumDescriptor() ([]byte, []int) {
	return file_razpravljalnica_razpravljalnica_proto_rawDescGZIP(), []int{1}
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_razpravljalnica_razpravljalnica_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_razpravljalnica_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_razpravljalnica_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Topic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Topic) Reset() {
	*x = Topic{}
	mi := &file_razpravljalnica_razpravljalnica_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topic) ProtoMessage() {}

func (x *Topic) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_razpravljalnica_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topic.ProtoReflect.Descriptor instead.
func (*Topic) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_razpravljalnica_proto_rawDescGZIP(), []int{1}
}

func (x *Topic) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Topic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TopicId       int64                  `protobuf:"varint,2,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Likes         int32                  `protobuf:"varint,6,opt,name=likes,proto3" json:"likes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_razpravljalnica_razpravljalnica_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_razpravljalnica_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_razpravljalnica_proto_rawDescGZIP(), []int{2}
}

func (x *Message) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Message) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *Message) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Message) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Message) GetLikes() int32 {
	if x != nil {
		return x.Likes
	}
	return 0
}

type Like struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       int64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	MessageId     int64                  `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Like) Reset() {
	*x = Like{}
	mi := &file_razpravljalnica_razpravljalnica_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Like) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Like) ProtoMessage() {}

func (x *Like) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_razpravljalnica_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Like.ProtoReflect.Descriptor instead.
func (*Like) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_razpravljalnica_proto_rawDescGZIP(), []int{3}
}

func (x *Like) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *Like) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *Like) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Role          NodeRole               `protobuf:"varint,3,opt,name=role,proto3,enum=razpravljalnica.NodeRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_razpravljalnica_razpravljalnica_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_razpravljalnica_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_razpravljalnica_proto_rawDescGZIP(), []int{4}
}

func (x *NodeInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NodeInfo) GetRole() NodeRole {
	if x != nil {
		return x.Role
	}
	return NodeRole_HEAD
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_razpravljalnica_razpravljalnica_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_razpravljalnica_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_razpravljalnica_proto_rawDescGZIP(), []int{5}
}

func (x *CreateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopicRequest) Reset() {
	*x = CreateTopicRequest{}
	mi := &file_razpravljalnica_razpravljalnica_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicRequest) ProtoMessage() {}

func (x *CreateTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_razpravljalnica_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicRequest.ProtoReflect.Descriptor instead.
func (*CreateTopicRequest) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_razpravljalnica_proto_rawDescGZIP(), []int{6}
}

func (x *CreateTopicRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PostMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       int64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostMessageRequest) Reset() {
	*x = PostMessageRequest{}
	mi := &file_razpravljalnica_razpravljalnica_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMessageRequest) ProtoMessage() {}

func (x *PostMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_razpravljalnica_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMessageRequest.ProtoReflect.Descriptor instead.
func (*PostMessageRequest) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_razpravljalnica_proto_rawDescGZIP(), []int{7}
}

func (x *PostMessageRequest) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *PostMessageRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PostMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type LikeMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       int64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	MessageId     int64                  `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeMessageRequest) Reset() {
	*x = LikeMessageRequest{}
	mi := &file_razpravljalnica_razpravljalnica_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeMessageRequest) ProtoMessage() {}

func (x *LikeMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_razpravljalnica_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeMessageRequest.ProtoReflect.Descriptor instead.
func (*LikeMessageRequest) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_razpravljalnica_proto_rawDescGZIP(), []int{8}
}

func (x *LikeMessageRequest) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *LikeMessageRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *LikeMessageRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListTopicsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []*Topic               `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTopicsResponse) Reset() {
	*x = ListTopicsResponse{}
	mi := &file_razpravljalnica_razpravljalnica_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTopicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopicsResponse) ProtoMessage() {}

func (x *ListTopicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_razpravljalnica_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopicsResponse.ProtoReflect.Descriptor instead.
func (*ListTopicsResponse) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_razpravljalnica_proto_rawDescGZIP(), []int{9}
}

func (x *ListTopicsResponse) GetTopics() []*Topic {
	if x != nil {
		return x.Topics
	}
	return nil
}

type GetMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       int64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	FromMessageId int64                  `protobuf:"varint,2,opt,name=from_message_id,json=fromMessageId,proto3" json:"from_message_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesRequest) Reset() {
	*x = GetMessagesRequest{}
	mi := &file_razpravljalnica_razpravljalnica_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesRequest) ProtoMessage() {}

func (x *GetMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_razpravljalnica_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_razpravljalnica_proto_rawDescGZIP(), []int{10}
}

func (x *GetMessagesRequest) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *GetMessagesRequest) GetFromMessageId() int64 {
	if x != nil {
		return x.FromMessageId
	}
	return 0
}

func (x *GetMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesResponse) Reset() {
	*x = GetMessagesResponse{}
	mi := &file_razpravljalnica_razpravljalnica_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesResponse) ProtoMessage() {}

func (x *GetMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_razpravljalnica_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_razpravljalnica_proto_rawDescGZIP(), []int{11}
}

func (x *GetMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type SubscribeTopicRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TopicId        []int64                `protobuf:"varint,1,rep,packed,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	UserId         int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FromMessageId  int64                  `protobuf:"varint,3,opt,name=from_message_id,json=fromMessageId,proto3" json:"from_message_id,omitempty"`
	SubscribeToken string                 `protobuf:"bytes,4,opt,name=subscribe_token,json=subscribeToken,proto3" json:"subscribe_token,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubscribeTopicRequest) Reset() {
	*x = SubscribeTopicRequest{}
	mi := &file_razpravljalnica_razpravljalnica_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeTopicRequest) ProtoMessage() {}

func (x *SubscribeTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_razpravljalnica_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeTopicRequest.ProtoReflect.Descriptor instead.
func (*SubscribeTopicRequest) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_razpravljalnica_proto_rawDescGZIP(), []int{12}
}

func (x *SubscribeTopicRequest) GetTopicId() []int64 {
	if x != nil {
		return x.TopicId
	}
	return nil
}

func (x *SubscribeTopicRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SubscribeTopicRequest) GetFromMessageId() int64 {
	if x != nil {
		return x.FromMessageId
	}
	return 0
}

func (x *SubscribeTopicRequest) GetSubscribeToken() string {
	if x != nil {
		return x.SubscribeToken
	}
	return ""
}

type SubscriptionNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TopicId       []int64                `protobuf:"varint,2,rep,packed,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionNodeRequest) Reset() {
	*x = SubscriptionNodeRequest{}
	mi := &file_razpravljalnica_razpravljalnica_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionNodeRequest) ProtoMessage() {}

func (x *SubscriptionNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_razpravljalnica_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionNodeRequest.ProtoReflect.Descriptor instead.
func (*SubscriptionNodeRequest) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_razpravljalnica_proto_rawDescGZIP(), []int{13}
}

func (x *SubscriptionNodeRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SubscriptionNodeRequest) GetTopicId() []int64 {
	if x != nil {
		return x.TopicId
	}
	return nil
}

type SubscriptionNodeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscribeToken string                 `protobuf:"bytes,1,opt,name=subscribe_token,json=subscribeToken,proto3" json:"subscribe_token,omitempty"`
	Node           *NodeInfo              `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubscriptionNodeResponse) Reset() {
	*x = SubscriptionNodeResponse{}
	mi := &file_razpravljalnica_razpravljalnica_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionNodeResponse) ProtoMessage() {}

func (x *SubscriptionNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_razpravljalnica_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionNodeResponse.ProtoReflect.Descriptor instead.
func (*SubscriptionNodeResponse) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_razpravljalnica_proto_rawDescGZIP(), []int{14}
}

func (x *SubscriptionNodeResponse) GetSubscribeToken() string {
	if x != nil {
		return x.SubscribeToken
	}
	return ""
}

func (x *SubscriptionNodeResponse) GetNode() *NodeInfo {
	if x != nil {
		return x.Node
	}
	return nil
}

type MessageEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SequenceNumber int64                  `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Op             OpType                 `protobuf:"varint,2,opt,name=op,proto3,enum=razpravljalnica.OpType" json:"op,omitempty"`
	Message        *Message               `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	EventAt        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=event_at,json=eventAt,proto3" json:"event_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageEvent) Reset() {
	*x = MessageEvent{}
	mi := &file_razpravljalnica_razpravljalnica_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEvent) ProtoMessage() {}

func (x *MessageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_razpravljalnica_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageEvent.ProtoReflect.Descriptor instead.
func (*MessageEvent) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_razpravljalnica_proto_rawDescGZIP(), []int{15}
}

func (x *MessageEvent) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *MessageEvent) GetOp() OpType {
	if x != nil {
		return x.Op
	}
	return OpType_OP_POST
}

func (x *MessageEvent) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *MessageEvent) GetEventAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EventAt
	}
	return nil
}

type GetClusterStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Head          *NodeInfo              `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	Tail          *NodeInfo              `protobuf:"bytes,2,opt,name=tail,proto3" json:"tail,omitempty"`
	Chain         []*NodeInfo            `protobuf:"bytes,3,rep,name=chain,proto3" json:"chain,omitempty"` // All nodes in order: head -> ... -> tail
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterStateResponse) Reset() {
	*x = GetClusterStateResponse{}
	mi := &file_razpravljalnica_razpravljalnica_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterStateResponse) ProtoMessage() {}

func (x *GetClusterStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_razpravljalnica_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterStateResponse.ProtoReflect.Descriptor instead.
func (*GetClusterStateResponse) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_razpravljalnica_proto_rawDescGZIP(), []int{16}
}

func (x *GetClusterStateResponse) GetHead() *NodeInfo {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *GetClusterStateResponse) GetTail() *NodeInfo {
	if x != nil {
		return x.Tail
	}
	return nil
}

func (x *GetClusterStateResponse) GetChain() []*NodeInfo {
	if x != nil {
		return x.Chain
	}
	return nil
}

type RegisterNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_razpravljalnica_razpravljalnica_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_razpravljalnica_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_razpravljalnica_proto_rawDescGZIP(), []int{17}
}

func (x *RegisterNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterNodeRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type RegisterNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AssignedRole  *NodeInfo              `protobuf:"bytes,2,opt,name=assigned_role,json=assignedRole,proto3" json:"assigned_role,omitempty"`
	Successor     *NodeInfo              `protobuf:"bytes,3,opt,name=successor,proto3" json:"successor,omitempty"` // Next node in chain (if not tail)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_razpravljalnica_razpravljalnica_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_razpravljalnica_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_razpravljalnica_proto_rawDescGZIP(), []int{18}
}

func (x *RegisterNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterNodeResponse) GetAssignedRole() *NodeInfo {
	if x != nil {
		return x.AssignedRole
	}
	return nil
}

func (x *RegisterNodeResponse) GetSuccessor() *NodeInfo {
	if x != nil {
		return x.Successor
	}
	return nil
}

type WriteOperation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SequenceNumber int64                  `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	OpType         OpType                 `protobuf:"varint,2,opt,name=op_type,json=opType,proto3,enum=razpravljalnica.OpType" json:"op_type,omitempty"`
	// Types that are valid to be assigned to Operation:
	//
	//	*WriteOperation_CreateUser
	//	*WriteOperation_CreateTopic
	//	*WriteOperation_PostMessage
	//	*WriteOperation_LikeMessage
	Operation     isWriteOperation_Operation `protobuf_oneof:"operation"`
	Timestamp     *timestamppb.Timestamp     `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteOperation) Reset() {
	*x = WriteOperation{}
	mi := &file_razpravljalnica_razpravljalnica_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteOperation) ProtoMessage() {}

func (x *WriteOperation) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_razpravljalnica_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteOperation.ProtoReflect.Descriptor instead.
func (*WriteOperation) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_razpravljalnica_proto_rawDescGZIP(), []int{19}
}

func (x *WriteOperation) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *WriteOperation) GetOpType() OpType {
	if x != nil {
		return x.OpType
	}
	return OpType_OP_POST
}

func (x *WriteOperation) GetOperation() isWriteOperation_Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *WriteOperation) GetCreateUser() *CreateUserRequest {
	if x != nil {
		if x, ok := x.Operation.(*WriteOperation_CreateUser); ok {
			return x.CreateUser
		}
	}
	return nil
}

func (x *WriteOperation) GetCreateTopic() *CreateTopicRequest {
	if x != nil {
		if x, ok := x.Operation.(*WriteOperation_CreateTopic); ok {
			return x.CreateTopic
		}
	}
	return nil
}

func (x *WriteOperation) GetPostMessage() *PostMessageRequest {
	if x != nil {
		if x, ok := x.Operation.(*WriteOperation_PostMessage); ok {
			return x.PostMessage
		}
	}
	return nil
}

func (x *WriteOperation) GetLikeMessage() *LikeMessageRequest {
	if x != nil {
		if x, ok := x.Operation.(*WriteOperation_LikeMessage); ok {
			return x.LikeMessage
		}
	}
	return nil
}

func (x *WriteOperation) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type isWriteOperation_Operation interface {
	isWriteOperation_Operation()
}

type WriteOperation_CreateUser struct {
	CreateUser *CreateUserRequest `protobuf:"bytes,3,opt,name=create_user,json=createUser,proto3,oneof"`
}

type WriteOperation_CreateTopic struct {
	CreateTopic *CreateTopicRequest `protobuf:"bytes,4,opt,name=create_topic,json=createTopic,proto3,oneof"`
}

type WriteOperation_PostMessage struct {
	PostMessage *PostMessageRequest `protobuf:"bytes,5,opt,name=post_message,json=postMessage,proto3,oneof"`
}

type WriteOperation_LikeMessage struct {
	LikeMessage *LikeMessageRequest `protobuf:"bytes,6,opt,name=like_message,json=likeMessage,proto3,oneof"`
}

func (*WriteOperation_CreateUser) isWriteOperation_Operation() {}

func (*WriteOperation_CreateTopic) isWriteOperation_Operation() {}

func (*WriteOperation_PostMessage) isWriteOperation_Operation() {}

func (*WriteOperation_LikeMessage) isWriteOperation_Operation() {}

type WriteAck struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SequenceNumber int64                  `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Success        bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error          string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WriteAck) Reset() {
	*x = WriteAck{}
	mi := &file_razpravljalnica_razpravljalnica_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteAck) ProtoMessage() {}

func (x *WriteAck) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_razpravljalnica_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteAck.ProtoReflect.Descriptor instead.
func (*WriteAck) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_razpravljalnica_proto_rawDescGZIP(), []int{20}
}

func (x *WriteAck) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *WriteAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WriteAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	LastSequence  int64                  `protobuf:"varint,2,opt,name=last_sequence,json=lastSequence,proto3" json:"last_sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_razpravljalnica_razpravljalnica_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_razpravljalnica_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_razpravljalnica_proto_rawDescGZIP(), []int{21}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetLastSequence() int64 {
	if x != nil {
		return x.LastSequence
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Alive         bool                   `protobuf:"varint,2,opt,name=alive,proto3" json:"alive,omitempty"`
	LastSequence  int64                  `protobuf:"varint,3,opt,name=last_sequence,json=lastSequence,proto3" json:"last_sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_razpravljalnica_razpravljalnica_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_razpravljalnica_razpravljalnica_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_razpravljalnica_razpravljalnica_proto_rawDescGZIP(), []int{22}
}

func (x *HeartbeatResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatResponse) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *HeartbeatResponse) GetLastSequence() int64 {
	if x != nil {
		return x.LastSequence
	}
	return 0
}

var File_razpravljalnica_razpravljalnica_proto protoreflect.FileDescriptor

const file_razpravljalnica_razpravljalnica_proto_rawDesc = "" +
	"\n" +
	"%razpravljalnica/razpravljalnica.proto\x12\x0frazpravljalnica\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"*\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"+\n" +
	"\x05Topic\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xb2\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\btopic_id\x18\x02 \x01(\x03R\atopicId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x14\n" +
	"\x05likes\x18\x06 \x01(\x05R\x05likes\"Y\n" +
	"\x04Like\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x03R\atopicId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x03R\tmessageId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\"l\n" +
	"\bNodeInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12-\n" +
	"\x04role\x18\x03 \x01(\x0e2\x19.razpravljalnica.NodeRoleR\x04role\"'\n" +
	"\x11CreateUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"(\n" +
	"\x12CreateTopicRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\\\n" +
	"\x12PostMessageRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x03R\atopicId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"g\n" +
	"\x12LikeMessageRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x03R\atopicId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x03R\tmessageId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\"D\n" +
	"\x12ListTopicsResponse\x12.\n" +
	"\x06topics\x18\x01 \x03(\v2\x16.razpravljalnica.TopicR\x06topics\"m\n" +
	"\x12GetMessagesRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x03R\atopicId\x12&\n" +
	"\x0ffrom_message_id\x18\x02 \x01(\x03R\rfromMessageId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"K\n" +
	"\x13GetMessagesResponse\x124\n" +
	"\bmessages\x18\x01 \x03(\v2\x18.razpravljalnica.MessageR\bmessages\"\x9c\x01\n" +
	"\x15SubscribeTopicRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x03(\x03R\atopicId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12&\n" +
	"\x0ffrom_message_id\x18\x03 \x01(\x03R\rfromMessageId\x12'\n" +
	"\x0fsubscribe_token\x18\x04 \x01(\tR\x0esubscribeToken\"M\n" +
	"\x17SubscriptionNodeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\btopic_id\x18\x02 \x03(\x03R\atopicId\"r\n" +
	"\x18SubscriptionNodeResponse\x12'\n" +
	"\x0fsubscribe_token\x18\x01 \x01(\tR\x0esubscribeToken\x12-\n" +
	"\x04node\x18\x02 \x01(\v2\x19.razpravljalnica.NodeInfoR\x04node\"\xcb\x01\n" +
	"\fMessageEvent\x12'\n" +
	"\x0fsequence_number\x18\x01 \x01(\x03R\x0esequenceNumber\x12'\n" +
	"\x02op\x18\x02 \x01(\x0e2\x17.razpravljalnica.OpTypeR\x02op\x122\n" +
	"\amessage\x18\x03 \x01(\v2\x18.razpravljalnica.MessageR\amessage\x125\n" +
	"\bevent_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aeventAt\"\xa8\x01\n" +
	"\x17GetClusterStateResponse\x12-\n" +
	"\x04head\x18\x01 \x01(\v2\x19.razpravljalnica.NodeInfoR\x04head\x12-\n" +
	"\x04tail\x18\x02 \x01(\v2\x19.razpravljalnica.NodeInfoR\x04tail\x12/\n" +
	"\x05chain\x18\x03 \x03(\v2\x19.razpravljalnica.NodeInfoR\x05chain\"H\n" +
	"\x13RegisterNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"\xa9\x01\n" +
	"\x14RegisterNodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12>\n" +
	"\rassigned_role\x18\x02 \x01(\v2\x19.razpravljalnica.NodeInfoR\fassignedRole\x127\n" +
	"\tsuccessor\x18\x03 \x01(\v2\x19.razpravljalnica.NodeInfoR\tsuccessor\"\xd7\x03\n" +
	"\x0eWriteOperation\x12'\n" +
	"\x0fsequence_number\x18\x01 \x01(\x03R\x0esequenceNumber\x120\n" +
	"\aop_type\x18\x02 \x01(\x0e2\x17.razpravljalnica.OpTypeR\x06opType\x12E\n" +
	"\vcreate_user\x18\x03 \x01(\v2\".razpravljalnica.CreateUserRequestH\x00R\n" +
	"createUser\x12H\n" +
	"\fcreate_topic\x18\x04 \x01(\v2#.razpravljalnica.CreateTopicRequestH\x00R\vcreateTopic\x12H\n" +
	"\fpost_message\x18\x05 \x01(\v2#.razpravljalnica.PostMessageRequestH\x00R\vpostMessage\x12H\n" +
	"\flike_message\x18\x06 \x01(\v2#.razpravljalnica.LikeMessageRequestH\x00R\vlikeMessage\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestampB\v\n" +
	"\toperation\"c\n" +
	"\bWriteAck\x12'\n" +
	"\x0fsequence_number\x18\x01 \x01(\x03R\x0esequenceNumber\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"P\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12#\n" +
	"\rlast_sequence\x18\x02 \x01(\x03R\flastSequence\"g\n" +
	"\x11HeartbeatResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05alive\x18\x02 \x01(\bR\x05alive\x12#\n" +
	"\rlast_sequence\x18\x03 \x01(\x03R\flastSequence*\"\n" +
	"\x06OpType\x12\v\n" +
	"\aOP_POST\x10\x00\x12\v\n" +
	"\aOP_LIKE\x10\x01*0\n" +
	"\bNodeRole\x12\b\n" +
	"\x04HEAD\x10\x00\x12\x10\n" +
	"\fINTERMEDIATE\x10\x01\x12\b\n" +
	"\x04TAIL\x10\x022\xab\x05\n" +
	"\fMessageBoard\x12G\n" +
	"\n" +
	"CreateUser\x12\".razpravljalnica.CreateUserRequest\x1a\x15.razpravljalnica.User\x12J\n" +
	"\vCreateTopic\x12#.razpravljalnica.CreateTopicRequest\x1a\x16.razpravljalnica.Topic\x12L\n" +
	"\vPostMessage\x12#.razpravljalnica.PostMessageRequest\x1a\x18.razpravljalnica.Message\x12L\n" +
	"\vLikeMessage\x12#.razpravljalnica.LikeMessageRequest\x1a\x18.razpravljalnica.Message\x12j\n" +
	"\x13GetSubscriptionNode\x12(.razpravljalnica.SubscriptionNodeRequest\x1a).razpravljalnica.SubscriptionNodeResponse\x12I\n" +
	"\n" +
	"ListTopics\x12\x16.google.protobuf.Empty\x1a#.razpravljalnica.ListTopicsResponse\x12X\n" +
	"\vGetMessages\x12#.razpravljalnica.GetMessagesRequest\x1a$.razpravljalnica.GetMessagesResponse\x12Y\n" +
	"\x0eSubscribeTopic\x12&.razpravljalnica.SubscribeTopicRequest\x1a\x1d.razpravljalnica.MessageEvent0\x012\xc0\x01\n" +
	"\fControlPlane\x12S\n" +
	"\x0fGetClusterState\x12\x16.google.protobuf.Empty\x1a(.razpravljalnica.GetClusterStateResponse\x12[\n" +
	"\fRegisterNode\x12$.razpravljalnica.RegisterNodeRequest\x1a%.razpravljalnica.RegisterNodeResponse2\xf3\x01\n" +
	"\x10ChainReplication\x12L\n" +
	"\x0ePropagateWrite\x12\x1f.razpravljalnica.WriteOperation\x1a\x19.razpravljalnica.WriteAck\x12=\n" +
	"\bAckWrite\x12\x19.razpravljalnica.WriteAck\x1a\x16.google.protobuf.Empty\x12R\n" +
	"\tHeartbeat\x12!.razpravljalnica.HeartbeatRequest\x1a\".razpravljalnica.HeartbeatResponseB\x12Z\x10/razpravljalnicab\x06proto3"

var (
	file_razpravljalnica_razpravljalnica_proto_rawDescOnce sync.Once
	file_razpravljalnica_razpravljalnica_proto_rawDescData []byte
)

func file_razpravljalnica_razpravljalnica_proto_rawDescGZIP() []byte {
	file_razpravljalnica_razpravljalnica_proto_rawDescOnce.Do(func() {
		file_razpravljalnica_razpravljalnica_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_razpravljalnica_razpravljalnica_proto_rawDesc), len(file_razpravljalnica_razpravljalnica_proto_rawDesc)))
	})
	return file_razpravljalnica_razpravljalnica_proto_rawDescData
}

var file_razpravljalnica_razpravljalnica_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_razpravljalnica_razpravljalnica_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_razpravljalnica_razpravljalnica_proto_goTypes = []any{
	(OpType)(0),                      // 0: razpravljalnica.OpType
	(NodeRole)(0),                    // 1: razpravljalnica.NodeRole
	(*User)(nil),                     // 2: razpravljalnica.User
	(*Topic)(nil),                    // 3: razpravljalnica.Topic
	(*Message)(nil),                  // 4: razpravljalnica.Message
	(*Like)(nil),                     // 5: razpravljalnica.Like
	(*NodeInfo)(nil),                 // 6: razpravljalnica.NodeInfo
	(*CreateUserRequest)(nil),        // 7: razpravljalnica.CreateUserRequest
	(*CreateTopicRequest)(nil),       // 8: razpravljalnica.CreateTopicRequest
	(*PostMessageRequest)(nil),       // 9: razpravljalnica.PostMessageRequest
	(*LikeMessageRequest)(nil),       // 10: razpravljalnica.LikeMessageRequest
	(*ListTopicsResponse)(nil),       // 11: razpravljalnica.ListTopicsResponse
	(*GetMessagesRequest)(nil),       // 12: razpravljalnica.GetMessagesRequest
	(*GetMessagesResponse)(nil),      // 13: razpravljalnica.GetMessagesResponse
	(*SubscribeTopicRequest)(nil),    // 14: razpravljalnica.SubscribeTopicRequest
	(*SubscriptionNodeRequest)(nil),  // 15: razpravljalnica.SubscriptionNodeRequest
	(*SubscriptionNodeResponse)(nil), // 16: razpravljalnica.SubscriptionNodeResponse
	(*MessageEvent)(nil),             // 17: razpravljalnica.MessageEvent
	(*GetClusterStateResponse)(nil),  // 18: razpravljalnica.GetClusterStateResponse
	(*RegisterNodeRequest)(nil),      // 19: razpravljalnica.RegisterNodeRequest
	(*RegisterNodeResponse)(nil),     // 20: razpravljalnica.RegisterNodeResponse
	(*WriteOperation)(nil),           // 21: razpravljalnica.WriteOperation
	(*WriteAck)(nil),                 // 22: razpravljalnica.WriteAck
	(*HeartbeatRequest)(nil),         // 23: razpravljalnica.HeartbeatRequest
	(*HeartbeatResponse)(nil),        // 24: razpravljalnica.HeartbeatResponse
	(*timestamppb.Timestamp)(nil),    // 25: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 26: google.protobuf.Empty
}
var file_razpravljalnica_razpravljalnica_proto_depIdxs = []int32{
	25, // 0: razpravljalnica.Message.created_at:type_name -> google.protobuf.Timestamp
	1,  // 1: razpravljalnica.NodeInfo.role:type_name -> razpravljalnica.NodeRole
	3,  // 2: razpravljalnica.ListTopicsResponse.topics:type_name -> razpravljalnica.Topic
	4,  // 3: razpravljalnica.GetMessagesResponse.messages:type_name -> razpravljalnica.Message
	6,  // 4: razpravljalnica.SubscriptionNodeResponse.node:type_name -> razpravljalnica.NodeInfo
	0,  // 5: razpravljalnica.MessageEvent.op:type_name -> razpravljalnica.OpType
	4,  // 6: razpravljalnica.MessageEvent.message:type_name -> razpravljalnica.Message
	25, // 7: razpravljalnica.MessageEvent.event_at:type_name -> google.protobuf.Timestamp
	6,  // 8: razpravljalnica.GetClusterStateResponse.head:type_name -> razpravljalnica.NodeInfo
	6,  // 9: razpravljalnica.GetClusterStateResponse.tail:type_name -> razpravljalnica.NodeInfo
	6,  // 10: razpravljalnica.GetClusterStateResponse.chain:type_name -> razpravljalnica.NodeInfo
	6,  // 11: razpravljalnica.RegisterNodeResponse.assigned_role:type_name -> razpravljalnica.NodeInfo
	6,  // 12: razpravljalnica.RegisterNodeResponse.successor:type_name -> razpravljalnica.NodeInfo
	0,  // 13: razpravljalnica.WriteOperation.op_type:type_name -> razpravljalnica.OpType
	7,  // 14: razpravljalnica.WriteOperation.create_user:type_name -> razpravljalnica.CreateUserRequest
	8,  // 15: razpravljalnica.WriteOperation.create_topic:type_name -> razpravljalnica.CreateTopicRequest
	9,  // 16: razpravljalnica.WriteOperation.post_message:type_name -> razpravljalnica.PostMessageRequest
	10, // 17: razpravljalnica.WriteOperation.like_message:type_name -> razpravljalnica.LikeMessageRequest
	25, // 18: razpravljalnica.WriteOperation.timestamp:type_name -> google.protobuf.Timestamp
	7,  // 19: razpravljalnica.MessageBoard.CreateUser:input_type -> razpravljalnica.CreateUserRequest
	8,  // 20: razpravljalnica.MessageBoard.CreateTopic:input_type -> razpravljalnica.CreateTopicRequest
	9,  // 21: razpravljalnica.MessageBoard.PostMessage:input_type -> razpravljalnica.PostMessageRequest
	10, // 22: razpravljalnica.MessageBoard.LikeMessage:input_type -> razpravljalnica.LikeMessageRequest
	15, // 23: razpravljalnica.MessageBoard.GetSubscriptionNode:input_type -> razpravljalnica.SubscriptionNodeRequest
	26, // 24: razpravljalnica.MessageBoard.ListTopics:input_type -> google.protobuf.Empty
	12, // 25: razpravljalnica.MessageBoard.GetMessages:input_type -> razpravljalnica.GetMessagesRequest
	14, // 26: razpravljalnica.MessageBoard.SubscribeTopic:input_type -> razpravljalnica.SubscribeTopicRequest
	26, // 27: razpravljalnica.ControlPlane.GetClusterState:input_type -> google.protobuf.Empty
	19, // 28: razpravljalnica.ControlPlane.RegisterNode:input_type -> razpravljalnica.RegisterNodeRequest
	21, // 29: razpravljalnica.ChainReplication.PropagateWrite:input_type -> razpravljalnica.WriteOperation
	22, // 30: razpravljalnica.ChainReplication.AckWrite:input_type -> razpravljalnica.WriteAck
	23, // 31: razpravljalnica.ChainReplication.Heartbeat:input_type -> razpravljalnica.HeartbeatRequest
	2,  // 32: razpravljalnica.MessageBoard.CreateUser:output_type -> razpravljalnica.User
	3,  // 33: razpravljalnica.MessageBoard.CreateTopic:output_type -> razpravljalnica.Topic
	4,  // 34: razpravljalnica.MessageBoard.PostMessage:output_type -> razpravljalnica.Message
	4,  // 35: razpravljalnica.MessageBoard.LikeMessage:output_type -> razpravljalnica.Message
	16, // 36: razpravljalnica.MessageBoard.GetSubscriptionNode:output_type -> razpravljalnica.SubscriptionNodeResponse
	11, // 37: razpravljalnica.MessageBoard.ListTopics:output_type -> razpravljalnica.ListTopicsResponse
	13, // 38: razpravljalnica.MessageBoard.GetMessages:output_type -> razpravljalnica.GetMessagesResponse
	17, // 39: razpravljalnica.MessageBoard.SubscribeTopic:output_type -> razpravljalnica.MessageEvent
	18, // 40: razpravljalnica.ControlPlane.GetClusterState:output_type -> razpravljalnica.GetClusterStateResponse
	20, // 41: razpravljalnica.ControlPlane.RegisterNode:output_type -> razpravljalnica.RegisterNodeResponse
	22, // 42: razpravljalnica.ChainReplication.PropagateWrite:output_type -> razpravljalnica.WriteAck
	26, // 43: razpravljalnica.ChainReplication.AckWrite:output_type -> google.protobuf.Empty
	24, // 44: razpravljalnica.ChainReplication.Heartbeat:output_type -> razpravljalnica.HeartbeatResponse
	32, // [32:45] is the sub-list for method output_type
	19, // [19:32] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_razpravljalnica_razpravljalnica_proto_init() }
func file_razpravljalnica_razpravljalnica_proto_init() {
	if File_razpravljalnica_razpravljalnica_proto != nil {
		return
	}
	file_razpravljalnica_razpravljalnica_proto_msgTypes[19].OneofWrappers = []any{
		(*WriteOperation_CreateUser)(nil),
		(*WriteOperation_CreateTopic)(nil),
		(*WriteOperation_PostMessage)(nil),
		(*WriteOperation_LikeMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_razpravljalnica_razpravljalnica_proto_rawDesc), len(file_razpravljalnica_razpravljalnica_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_razpravljalnica_razpravljalnica_proto_goTypes,
		DependencyIndexes: file_razpravljalnica_razpravljalnica_proto_depIdxs,
		EnumInfos:         file_razpravljalnica_razpravljalnica_proto_enumTypes,
		MessageInfos:      file_razpravljalnica_razpravljalnica_proto_msgTypes,
	}.Build()
	File_razpravljalnica_razpravljalnica_proto = out.File
	file_razpravljalnica_razpravljalnica_proto_goTypes = nil
	file_razpravljalnica_razpravljalnica_proto_depIdxs = nil
}
